name = "motplusplus-site"
main = "worker.js"
compatibility_date = "2024-09-23"
routes = [
  { pattern = "motplusplusplus.com", custom_domain = true },
  { pattern = "www.motplusplusplus.com", custom_domain = true },
]

[assets]
directory = "out"
binding = "ASSETS"
