#!/usr/bin/env python3
"""
Generate a Cloudflare Pages _redirects file from events-data.json.
Maps old WordPress URLs (/YYYY/MM/DD/slug/) → new site (/events/slug).
Run after scrape-events.py and patch-events.py complete.
"""

import json, os, re
from urllib.parse import urlparse

IN  = os.path.join(os.path.dirname(__file__), '..', 'events-data.json')
OUT = os.path.join(os.path.dirname(__file__), '..', 'public', '_redirects')

def main():
    with open(IN, encoding='utf-8') as f:
        events = json.load(f)

    lines = [
        "# Auto-generated: old WordPress URLs → new event pages",
        "# Generated by scripts/generate-redirects.py",
        "",
    ]

    seen_paths = set()
    redirect_count = 0

    for e in events:
        wp_link = e.get('wpLink', '')
        slug    = e.get('slug', '')
        if not wp_link or not slug:
            continue

        parsed = urlparse(wp_link)
        # WP path: /YYYY/MM/DD/post-slug/
        old_path = parsed.path.rstrip('/')
        if not old_path or old_path in seen_paths:
            continue

        new_path = f"/events/{slug}"
        lines.append(f"{old_path}  {new_path}  301")
        seen_paths.add(old_path)
        redirect_count += 1

    with open(OUT, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')

    print(f"Written {redirect_count} redirects to public/_redirects")

if __name__ == '__main__':
    main()
